--Hoy veremos Disparadores
--EJEMPLO 1
create table mayores(ID INTEGER PRIMARY KEY,
                    NOMBRE VARCHAR2(60),
                    EDAD INTEGER
                    );
                    
CREATE OR REPLACE TRIGGER DISP_MAYORES BEFORE INSERT ON MAYORES
FOR EACH ROW --GARANTIZA EL DISPARO EN CADA FILA, SI SE EJECUTA UN CURSOR
BEGIN
IF :NEW.EDAD<18 THEN
raise_application_error(-20000, 'EDAD INCORRECTA'); --raise_application es un excepcion de oracle
END IF;
END;
/

INSERT INTO MAYORES VALUES(1,'JUAN',20);

SELECT * FROM MAYORES;

INSERT INTO MAYORES VALUES(2,'ANA',16);

--EJEMPLO 2

CREATE TABLE NOMINA(ID INTEGER PRIMARY KEY,
                    SUELDO_BASE FLOAT,
                    HORAS_LABORADAS INTEGER,
                    DEPOSITO FLOAT);
                    
        
DELETE FROM NOMINA;
INSERT INTO NOMINA VALUES(1,2000,20,28000);
INSERT INTO NOMINA VALUES(2,1000,16,50000);

SELECT * FROM NOMINA;

CREATE OR REPLACE TRIGGER DISP_NOMINA BEFORE UPDATE ON NOMINA
FOR EACH ROW
BEGIN
--INICIAMOS LA LOGICA DEL DISPARADOR
:NEW.DEPOSITO:= :OLD.DEPOSITO+:NEW.HORAS_LABORADAS * :OLD.SUELDO_BASE;
END;
/

UPDATE NOMINA SET HORAS_LABORADAS=20 WHERE ID=1;

                    